# Generated by Django 3.2 on 2025-04-28 18:23

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=timezone.now),  # Changed default to timezone.now
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=timezone.now),  # Changed default to timezone.now
        ),
    ]