# Generated by Django 5.2 on 2025-05-06 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20250504_1103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 6, 9, 5, 56, 935373, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 6, 9, 5, 56, 934373, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
